config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  root to: 'posts#index'

  authenticate :user, lambda { |u| u.user_type.name == 'Administrator' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :comments, except: [:index] do
    resources :comments, module: :comments, except: [:index]
  end
  resources :notifications, only: [:index] do
    member do
      patch :mark_as_read
    end
    collection do
      delete :destroy_all
    end
  end
  resources :posts do
    resources :comments, module: :posts, except: [:index]
    resource :like, module: :posts, only: [:update]
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, only: [:index] do
    member do
      patch :toggle_lock
    end
  end
end

app/models/comment.rb
# frozen_string_literal: true

# app/models/comment.rb
class Comment < ApplicationRecord
  include ActionView::RecordIdentifier

  has_many :comments, foreign_key: :parent_id, dependent: :destroy
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  belongs_to :parent, optional: true, class_name: 'Comment'
  has_rich_text :body

  validates :body, presence: true

  after_create_commit do
    broadcast_append_to [commentable, :comments],
                        target: "#{dom_id(parent || commentable)}_comments",
                        partial: 'comments/comment_with_replies'
  end

  after_update_commit do
    broadcast_replace_to self
  end

  after_destroy_commit do
    broadcast_remove_to self
    broadcast_action_to self, action: :remove, target: "#{dom_id(self)}_with_comments"
  end

  def reply_to_comment_or_post
    if parent_id
      "new_comment_on_#{parent.class.name.downcase}"
    else
      "new_comment_on_#{commentable_type.downcase}"
    end
  end
end

app/controllers/comments/comments_controller.rb
# frozen_string_literal: true

# Nested comments controller
module Comments
  # app/controller/posts/comments_controller.rb
  class CommentsController < ApplicationController
    include Commentable

    before_action :set_commentable

    private

    def set_commentable
      @parent = Comment.find(params[:comment_id])
      @commentable = @parent.commentable
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# app/controller/comments_controller.rb
# create action is in concerns folder
class CommentsController < ApplicationController
  before_action :set_comment

  def show; end

  def edit; end

  def update
    if @comment.update(comment_params)
      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = 'Comment was successfully updated.' }
        format.html { redirect_to @comment }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = 'Comment was successfully deleted.' }
      format.html { redirect_to @comment.commentable }
    end
  end

  private

  def set_comment
    @comment = current_user.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

# nested in posts
module Posts
  # app/controllers/posts/comments_controller.rb
  class CommentsController < ApplicationController
    include Commentable

    before_action :set_commentable

    private

    def set_commentable
      @commentable = Post.find(params[:post_id])
    end
  end
end

app/views/comments/_comment.html.erb
<%= turbo_stream_from comment %>
<%= turbo_frame_tag comment do %>
  <div class="flex justify-between mt-5">
    <div><%= comment.user.full_name %></div>
    <div><%= comment.body %></div>
    <div class="flex flex-col md:flex-row items-center text-center space-y-2 md:space-y-0">
      <%= link_to 'Edit', edit_comment_path(comment), class: 'md:mr-2 hover:cursor-pointer actions rounded-md hover:bg-blue-300 login-button px-2 pt-2 min-w-[75px]' %>
      <%= button_to "Delete", comment_path(comment), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, class: 'hover:cursor-pointer actions rounded-md hover:bg-red-300 login-button px-2 min-w-[75px]' %>
    </div>
  </div>
<% end %>

app/views/comments/_comment_with_replies.html.erb
<%= turbo_stream_from comment, :comments %>
<div class="pl-3" id="<%= dom_id(comment) %>_with_comments" data-controller="comment-reply">
  <%= render comment %>

  <div class="text-sm">
    <%= link_to 'Reply', '#', data: { action: "click->comment-reply#toggle" } %>
  </div>
  <hr />

  <div id="<%= dom_id(comment) %>_comments">
    <%= render partial: 'comments/form', locals: { commentable: comment, comment: Comment.new, data: { comment_reply_target: 'form' }, class: 'hidden' } %>
    <%= render partial: 'comments/comment_with_replies', collection: comment.comments, as: :comment %>
  </div>
</div>

app/views/comments/_form.html.erb
<% model = [local_assigns[:commentable], comment].compact %>
<%= form_with model: model,
  id: dom_id_for_records(*model),
  data: local_assigns[:data],
  class: ["my-4"] + Array.wrap(local_assigns[:class]) do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div class="text-red-500 font-bold"><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <%= form.rich_text_area :body, id: "#{dom_id_for_records(*model)}_body", class: 'comments-text-editor' %>
  <div class="flex items-center justify-between mt-5">
    <%= form.submit 'Submit', class: 'hover:cursor-pointer actions rounded-md hover:bg-blue-300 login-button px-5' %>
    <%= link_to 'Cancel', comment, class: 'flex items-center hover:cursor-pointer actions rounded-md hover:bg-red-300 login-button px-5' if form.object.persisted? %>
  </div>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.prepend "flash", partial: "/shared/flash_messages" %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render 'form', comment: @comment %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render @comment %>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.prepend "flash", partial: "/shared/flash_messages" %>