config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  root to: 'posts#index'

  authenticate :user, lambda { |u| u.user_type.name == 'Administrator' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :comments, except: [:index] do
    resources :comments, module: :comments, except: [:index]
  end
  resources :notifications, only: [:index] do
    member do
      patch :mark_as_read
    end
    collection do
      delete :destroy_all
    end
  end
  resources :posts do
    resources :comments, module: :posts, except: [:index]
    resource :like, module: :posts, only: [:update]
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, only: [:index] do
    member do
      patch :toggle_lock
    end
  end
end

app/models/notification.rb
# frozen_string_literal: true

# app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :actor, foreign_key: :actor_id, class_name: 'User'
  belongs_to :user
  belongs_to :targetable, polymorphic: true

  default_scope { order({ created_at: :desc }) }

  after_create_commit do
    broadcast_notification
  end

  private

  def broadcast_notification
    broadcast_replace_to [:notifications],
                         target: "notifications_list_#{user.id}",
                         partial: 'shared/notifications',
                         locals: { current_user: user }
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

# app/controller/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:mark_as_read]

  def index
    @notifications = current_user.notifications.where(read: false)
    respond_to do |format|
      format.json { render json: @notifications }
    end
  end

  def mark_as_read
    @notification.update(read: true)
    render turbo_stream: [turbo_stream.replace("notification_#{@notification.id}",
                                               partial: 'shared/notification_li',
                                               locals: { notification: @notification }),
                          turbo_stream.update('notification_counter',
                                              partial: 'shared/notification_navbar',
                                              locals: { current_user: @notification.user })]
  end

  def destroy_all
    @notifications = Notification.where(user: current_user)
    @notifications.destroy_all
    render turbo_stream: [turbo_stream.replace("notifications_#{current_user.id}",
                                               partial: 'shared/notifications',
                                               locals: { current_user: current_user }),
                          turbo_stream.update('notification_counter',
                                              partial: 'shared/notification_navbar',
                                              locals: { current_user: current_user })]
  end

  private

  def set_notification
    @notification = Notification.find(params[:id])
  end
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

# app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_colour(current_user)
    current_user.unread_notifications.count.positive? ? 'fill-current text-red-500' : ''
  end

  def notification_read(notification)
    notification.read? ? 'text-gray-100' : 'bg-gray-100 p-2 rounded-md'
  end
end

app/views/notifications/_new_comment_on_comment.html.erb
<%= "#{notification.actor.full_name} has replied to your comment on a post called " %>
<%= link_to notification.targetable.title, notification.targetable, target: "_blank", class: 'hover:underline' %>
<% if !notification.read? %>
  <%= button_to "Mark as read", mark_as_read_notification_path(notification), method: :patch %>
<% end %>

app/views/notifications/_new_comment_on_post.html.erb
<%= "#{notification.actor.full_name} has commented on your post called " %>
<%= link_to notification.targetable.title, notification.targetable, target: "_blank", class: 'hover:underline' %>
<% if !notification.read? %>
  <%= button_to "Mark as read", mark_as_read_notification_path(notification), method: :patch %>
<% end %>

app/views/notifications/_new_like_on_post.html.erb
<%= "#{notification.actor.full_name} likes your post called " %>
<%= link_to notification.targetable.title, notification.targetable, target: "_blank", class: 'hover:underline' %>
<% if !notification.read? %>
  <%= button_to "Mark as read", mark_as_read_notification_path(notification), method: :patch, class: 'hover:underline' %>
<% end %>