config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  root to: 'posts#index'

  authenticate :user, lambda { |u| u.user_type.name == 'Administrator' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :comments, except: [:index] do
    resources :comments, module: :comments, except: [:index]
  end
  resources :notifications, only: [:index] do
    member do
      patch :mark_as_read
    end
    collection do
      delete :destroy_all
    end
  end
  resources :posts do
    resources :comments, module: :posts, except: [:index]
    resource :like, module: :posts, only: [:update]
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, only: [:index] do
    member do
      patch :toggle_lock
    end
  end
end

app/models/post.rb
# frozen_string_literal: true

# app/models/post.rb
class Post < ApplicationRecord
  include MeiliSearch::Rails
  extend Pagy::Meilisearch
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :record, dependent: :destroy
  has_many :notifications, as: :targetable, dependent: :destroy
  belongs_to :post_type
  belongs_to :user
  validates_presence_of :content
  validates_presence_of :title

  has_rich_text :content

  default_scope { order(created_at: :desc) }

  meilisearch do
    attribute :title
    attribute :content do
      content.body.to_plain_text
    end
    attribute :user do
      user.full_name
    end
    attribute :comments do
      comments.map { |comment| comment.body.body.to_plain_text }
    end
    attribute :post_type do
      post_type.name
    end
    filterable_attributes %i[title content]
    sortable_attributes %i[created_at updated_at]
  end

  def liked_by?(user)
    likes.where(user: user).any?
  end

  def like(user)
    likes.where(user: user).first_or_create
  end

  def unlike(user)
    likes.where(user: user).destroy_all
  end
end

app/models/post_type.rb
# frozen_string_literal: true

# app/models/post_type.rb
class PostType < Type
  has_many :posts
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

# nested in posts
module Posts
  # app/controllers/posts/comments_controller.rb
  class CommentsController < ApplicationController
    include Commentable

    before_action :set_commentable

    private

    def set_commentable
      @commentable = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

# nested in posts
module Posts
  # app/controllers/posts/likes_controller.rb
  class LikesController < ApplicationController
    before_action :set_post
    include ActionView::RecordIdentifier

    def update
      if @post.liked_by?(current_user)
        @post.unlike(current_user)
      else
        @post.like(current_user)
        NotificationService.new(current_user, @post, 'new_like_on_post').create_new_notification
      end

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(dom_id(@post, :likes),
                                                    partial: 'posts/likes', locals: { post: @post })
        end
      end
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# app/controller/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    posts = Post.pagy_search(params[:query])
    @post1 = Post.all.sample
    @post2 = Post.all.sample
    @post3 = Post.all.sample
    @pagy, @posts = pagy_meilisearch(posts, limit: 25)
  rescue Pagy::OverflowError
    redirect_to posts_path(page: 1)
  end

  def show; end

  def new
    authorize @post = Post.new
  end

  def edit; end

  def create
    authorize @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      flash.now[:alert] = 'Post could not be created, please try again.'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      flash.now[:alert] = 'Post could not be updated, please try again.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.delete
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end

  private

  def set_post
    authorize @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title,
                                 :content,
                                 :user_id,
                                 :post_type_id)
  end
end

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div class="flex flex-col justify-center">
    <% if form.object.errors.any? %>
      <div>
        <% form.object.errors.full_messages.each do |message| %>
          <div class="text-red-500 font-bold"><%= message %></div>
        <% end %>
      </div>
    <% end %>  
    <%= form.label :post_type_id %>
    <%= form.select :post_type_id, options_for_select(PostType.pluck(:name, :id)) %>
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: 'customized-max-width', required: true %>
    <%= form.submit class: 'hover:cursor-pointer p-5 bg-blue-100 hover:bg-blue-300 my-5 rounded-md' %>
  </div>
<% end %>

app/views/posts/_hero.html.erb
<div data-controller="infinite-carousel" class="w-full z-0">
  <div class="relative h-64 overflow-hidden">
    <div class="absolute inset-0 flex items-center justify-center transition-transform duration-1000 ease-in-out transform" data-infinite-carousel-target="slide">
      <div class="w-full bg-blue-300 h-full flex flex-col items-center justify-center space-y-5">
        <h3 class="text-white text-2xl md:text-3xl font-bold"><%= post1.title %></h3>
        <h4 class="text-white text-xl md:text-2xl font-bold"><%= link_to 'Read more', post_path(post1) %></h4>
      </div>
    </div>
    <div class="absolute hidden inset-0 flex items-center justify-center transition-transform duration-1000 ease-in-out transform" data-infinite-carousel-target="slide">
      <div class="w-full bg-red-300 h-full flex flex-col items-center justify-center space-y-5">
        <h3 class="text-white text-2xl md:text-3xl font-bold"><%= post2.title %></h3>
        <h4 class="text-white text-xl md:text-2xl font-bold"><%= link_to 'Read more', post_path(post2) %></h4>
      </div>
    </div>
    <div class="absolute hidden inset-0 flex items-center justify-center transition-transform duration-1000 ease-in-out transform" data-infinite-carousel-target="slide">
      <div class="w-full bg-green-300 h-full flex flex-col items-center justify-center space-y-5">
        <h3 class="text-white text-2xl md:text-3xl font-bold"><%= post3.title %></h3>
        <h4 class="text-white text-xl md:text-2xl font-bold"><%= link_to 'Read more', post_path(post3) %></h4>
      </div>
    </div>
  </div>
</div>

app/views/posts/_likes.html.erb
<%= tag.div class: 'flex flex-col md:flex-row items-center justify-start md:space-x-5', id: dom_id(post, :likes) do %>
  <%= tag.div id: "#{dom_id(post, :likes)}_count" do %>
    <%= render partial: 'posts/likes_count', locals: { post: post } %>
  <% end %>
  <%= button_to like_button_text(post), post_like_path(post), method: :patch, class: "#{blue_or_red(post)} p-2 rounded-md min-w-[75px]" %>
<% end %>

app/views/posts/_likes_count.html.erb
<%= post.likes_count %>

app/views/posts/_post.html.erb
<div class="border-2 border-black rounded-md p-5 space-y-5 mx-5 my-5 index-post">
  <h2 class="m-0"><%= post.title %></h2>
  <p class="m-0"><%= truncate(post.content.to_plain_text, length: 300) %></p>
  <ul class="flex flex-row justify-center list-none space-x-5">
    <li><%= link_to 'View Post', post_path(post), class: 'hover:underline' %></li>
    <li><%= link_to 'Edit Post', edit_post_path(post), class: 'hover:underline' if policy(post).update? %></li>
  </ul>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/edit.html.erb
<div class="mx-5">
  <h1 class="m-5">Edit post</h1>
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<% unless @post1.nil? && @post2.nil? && @post3.nil? %>
  <%= render 'hero', post1: @post1, post2: @post2, post3: @post3 %>
<% end %>

<div class="h-full">
  <h1 class="p-5">All posts</h1>
  <div class="flex justify-center">
    <%= form_with url: posts_path, method: :get do |form| %>
      <%= form.search_field :query %>
      <%= form.button 'Search', class: 'rounded-md hover:bg-blue-300 login-button px-5' %>
    <% end %>
  </div>  
  <% @posts.each do |post| %>
    <div class="border-2 border-black rounded-md p-5 space-y-5 mx-5 my-5 index-post">
      <h2 class="m-0"><%= post.title %></h2>
      <p class="m-0"><%= truncate(post.content.to_plain_text, length: 300) %></p>
      <ul class="flex flex-row justify-center list-none space-x-5">
        <li><%= link_to 'View Post', post_path(post), class: 'hover:underline' %></li>
        <li><%= link_to 'Edit Post', edit_post_path(post), class: 'hover:underline' if policy(post).update? %></li>
      </ul>
    </div>
  <% end %>
</div>
<% if @pagy.count > @pagy.items %>
  <div class="my-10">
    <%== pagy_nav(@pagy) %>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="mx-5">
  <h1 class="m-5">New post</h1>
  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="m-5 show-view space-y-5">
  <h1 class="mb-5"><%= @post.title %></h1>
  <small>Written by <%= @post.user.full_name %> on <%= @post.created_at %></small>
  <p><%= @post.content %></p>
  <ul class="flex flex-row justify-center list-none space-x-5">
    <li><%= link_to 'Edit Post', edit_post_path(@post), class: 'hover:underline' %></li>
    <li><%= link_to 'All Posts', posts_path, class: 'hover:underline' %></li>
  </ul>
  <%= turbo_stream_from @post, :likes %>
  <%= render partial: 'likes', locals: { post: @post } %>
  
  <%= render partial: 'comments/form', locals: { comment: Comment.new, commentable: @post } %>

  <%= turbo_stream_from @post, :comments %>

  <%= tag.div id: "#{dom_id(@post)}_comments" do %>
    <%= render partial: 'comments/comment_with_replies', collection: @post.comments.where(parent_id: nil), as: :comment %>
  <% end %>
</div>