config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Sidekiq::Web.app_url = '/'

Rails.application.routes.draw do
  root to: 'posts#index'

  authenticate :user, lambda { |u| u.user_type.name == 'Administrator' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :comments, except: [:index] do
    resources :comments, module: :comments, except: [:index]
  end
  resources :notifications, only: [:index] do
    member do
      patch :mark_as_read
    end
    collection do
      delete :destroy_all
    end
  end
  resources :posts do
    resources :comments, module: :posts, except: [:index]
    resource :like, module: :posts, only: [:update]
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, only: [:index] do
    member do
      patch :toggle_lock
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer bg-blue-100 flex items-center justify-center">
    <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12">
        <h3 class="mb-4 text-3xl font-extrabold tracking-tight leading-none text-gray-900 md:text-4xl lg:text-5xl dark:text-white">Test blog</h3>
        <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">App made with RoR, Tailwind, Hotwire, Turbo, and Stimulus.</p>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<div 
data-controller="notifications">
	<nav class="flex lg:hidden items-center h-16 bg-blue-100">
		<button class="text-blue-600 p-3" data-action="click->notifications#hamburger">
      <svg class="block h-4 w-4 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" data-notifications-target="hamburger"></path>
      </svg>
      <svg data-notifications-target="cross" class="hidden fill-current" viewBox="0 0 490 490"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <polygon points="456.851,0 245,212.564 33.149,0 0.708,32.337 212.669,245.004 0.708,457.678 33.149,490 245,277.443 456.851,490 489.292,457.678 277.331,245.004 489.292,32.337 "></polygon> </g></svg>
		</button>
	</nav>
  <nav class="transition-opacity
              transition-height
              duration-300
              ease-in-out
              bg-blue-100
              py-5
              lg:py-0
              px-3
              lg:px-5
              opacity-0
              lg:opacity-100
              hidden
              flex flex-col
              lg:flex
              lg:flex-row
              lg:items-center
              md:justify-end
              lg:space-x-5
              lg:h-16"
       data-notifications-target="expand">
    <div id="notification_counter"><%= render '/shared/notification_navbar' if user_signed_in? %></div>
    <div class="hover:text-red-500"><%= link_to 'Posts', posts_path if user_signed_in? %></div>
    <div class="hover:text-red-500"><%= link_to 'New Post', new_post_path if user_signed_in? %></div>
    <div class="hover:text-red-500"><%= link_to 'Users', users_path if user_signed_in? && policy(:user).index? %></div>
    <div class="hover:text-red-500"><%= button_to('Sign Out', destroy_user_session_path, method: :delete) if user_signed_in? %></div>
  </nav>
  <%= turbo_stream_from :notifications %>
  <div class="h-0 overflow-auto transition-height duration-1000 ease-in-out bg-gray-300 bg-opacity-70"
       data-notifications-target="notifications">
    <% if user_signed_in? %>
      <%= turbo_frame_tag "notifications_#{current_user.id}" do %>
        <div id="<%= "notifications_list_#{current_user.id}" %>">
          <%= render '/shared/notifications' %>
        </div>
      <% end %>  
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <div class="sticky top-0 z-10">
      <%= render 'layouts/navbar' %>
      </div>
      <div id="flash">
        <%= render 'shared/flash_messages' %>
      </div>
      <main class="flex flex-col justify-center items-center main">
        <%= yield %>
      </main>
      <%= render 'layouts/footer' %>
  </body>
</html>